import { Property, Lead, BlogPost } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'The Emerald Villa',
    address: '123 Palm Grove, Beverly Hills',
    price: 850000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9T1shUXleeUqeshNca01pUUq-Lm3AJfsBSbZAAA10FPnW8uXG0px88zzuVg9M2xQ_RK1QpxwdAkeyFgBITH-0oFW0m8NHHJQC1L3921m_EPBM7uUQsCCTdKoJC9B6FhQJFpPd1PC8aRprtMFyZi4Xl7i3-LK3RWDqamMYHoeJUIlacPCtvZcSoLCAllnlZ05wX2jWAKSU3Mo6VVl7BYQ4h6QjB06p-6C7tTmKRaLpE2ImYKrDsMcX5aAV_TaF5J5kUOfV9uR_T4A',
    beds: 4,
    baths: 3,
    sqft: 2400,
    status: 'For Sale',
    tags: ['Selling Fast'],
    featured: true,
  },
  {
    id: '2',
    name: 'Skyline Heights',
    address: '45 Downtown Blvd, City Center',
    price: 425000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2-ITPECQUt5R_vxCokJF3LAo-PD0Pibbgey-H7u7Vaxk9uen4xFdhiwy5zCYlDjUdD6J8sCV_xBMIruLmvLyQ4RlCbQ8_RJj3dvSCPmBvrN3jdPfOm6qbShvMPsLVLuWeOSEUzMhIbSzM4PiEs1GuzxgIoVARwCs2hDjIpeVFKOJhIsLfjE46FsIqN1I7-h5Oj6V2hRWgDARIMQCQ2U5wL6kUtHmiOEsahXxGd9pV3kDfQyxrbUSE30WxY8PNxbpoRA1gcE6jBtI',
    beds: 2,
    baths: 2,
    sqft: 1100,
    status: 'For Sale',
    tags: ['New Listing'],
  },
  {
    id: '3',
    name: 'Oakwood Residence',
    address: '88 Oak Street, Suburbia',
    price: 3200,
    priceLabel: '/mo',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCsyJZfQ3-X0cgiGnAjNI2HVm1qd43Ke2C_FheEErWc1OnqJE25YOsz4e6zhIj2x4qvn3IP8hnsO3vj77n0i-HIpx9Q1bYPaBMPu_P-rEsyBTAI6r1aupOMr8vLFLqE8B8u3qiqsTYDMmulG_YRTYQgSmADPOOjcmvbJgo4z5zCEXl6of2CQqLBkvkFpAT_N4R_JN-9KgrVhAKjmTSrrgcRoxmc1gYB8QjUoQCYgx1H1rO6ZUln52VjEM0Xgi-oue9MJyiNAnj5tkE',
    beds: 3,
    baths: 2.5,
    sqft: 1850,
    status: 'For Rent',
    tags: ['For Rent'],
  },
  {
    id: '4',
    name: 'The Obsidian Cube',
    address: '77 Modern Lane, Arts District',
    price: 1250000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-maLMzSro9g0HlN1ueqsOirdShyzuAUruclk8aF3-R0oG5w09Z0w71cQABhDUdzU2y88zy37UImcE-1xdDSVSSchSHGjpcfBUle7aQ90NHvSX-juVmsMe49VKMoGMwQTnEgmbWd1rWgw46f87IrSFIgb0mFK10fSGG1Rb3yO-oKpeA97O5a_zuZ0VGqQS4vgUVtxDC9GalTsw94JTyWie5iFNGYaSjXNiCFHw3RHvRDNJFfR0XbN9sIEGBgyjIFEJz2AsDG50Nac',
    beds: 3,
    baths: 3,
    sqft: 2100,
    status: 'For Sale',
    tags: [],
    featured: true,
  },
  {
    id: '5',
    name: 'Riverstone Manor',
    address: '202 River Rd, Countryside',
    price: 670000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXRISvpC3J5JAzcy6Z43lrD_cFXjProVytCcwBanF3i7FvXgqqlYDejW2N2v_nbfQXICrdLNUO8KMPrKnTuKVz8MPsqqv0lJWqeA4tMcDlWL9lGQH_Zj6y3NZr0O3zo_araaYuvpyI7gaLizxtvNFLDihgnyZR632iI41T-hwt2fbJdQ-f0C6cTeFgKHxIEtyVeBWXqLifdZHG2EK9DAH_VQ7e15XlymjyI6L3of0g2m0Xm4PdRw3RNO9CKUf-7O47IPiPrA61mQg',
    beds: 5,
    baths: 4,
    sqft: 3200,
    status: 'For Sale',
    tags: ['Hot Deal'],
  },
  {
    id: '6',
    name: 'The Garden Cottage',
    address: '14 Maple Lane, Historic District',
    price: 295000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCM861Ha9XQxGdb8PMbJ-iw1rZL60fobDtFNgtRqTsbLBQpy_JWlq2rnf5UHYNqeBcwBS7I9eFEqnY-ebVELn_tO5iOBbTQYO7qOT0wYE34vZqrOq33R0kM-QIn1pJRLTyqcooBdGw1bzJRf73fkVAcprlXnn5nC1w_23HthXo3O9VLNYjtgdP9jYujMQQSYdikeC6NpfgfbLDZOfaQblU2j5qxLMGjYCiMmKcWPnJRoXC7YHGZYwIDapGFKKu0sPCKlRGog8oZ2ok',
    beds: 2,
    baths: 1,
    sqft: 950,
    status: 'For Sale',
    tags: [],
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@example.com',
    propertyInterest: 'The Modern Loft',
    propertyDetails: '2 Bed, 2 Bath - Downtown',
    budget: '$450,000 - $500,000',
    date: 'Oct 24, 2023',
    time: '10:30 AM',
    status: 'New',
    avatar: 'https://i.pravatar.cc/150?u=1'
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'm.chen88@example.com',
    propertyInterest: 'Suburban Family Home',
    propertyDetails: '4 Bed, 3 Bath - Oakwood',
    budget: '$850,000+',
    date: 'Oct 23, 2023',
    time: '4:15 PM',
    status: 'Pending Review',
    avatar: 'https://i.pravatar.cc/150?u=2'
  },
  {
    id: '3',
    name: 'David Ross',
    email: 'david.r@example.com',
    propertyInterest: 'Seaside Condo',
    propertyDetails: '1 Bed - Coastal View',
    budget: '$300,000',
    date: 'Oct 22, 2023',
    time: '9:00 AM',
    status: 'Contacted',
    avatar: 'https://i.pravatar.cc/150?u=3'
  },
  {
    id: '4',
    name: 'Emma Watson',
    email: 'emma.w@example.com',
    propertyInterest: 'Luxury Penthouse',
    propertyDetails: '3 Bed - City Center',
    budget: '$1,200,000',
    date: 'Oct 21, 2023',
    time: '2:45 PM',
    status: 'Scheduled Viewing',
    avatar: 'https://i.pravatar.cc/150?u=4'
  }
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Top 10 Emerging Neighborhoods for Real Estate Investment in 2024',
    excerpt: 'Discover the hidden gems in the real estate market that promise high ROI over the next decade. We analyze market trends and infrastructure plans.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.',
    author: 'Elena Rodriguez',
    authorAvatar: 'https://i.pravatar.cc/150?u=10',
    date: 'Oct 15, 2023',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    category: 'Market Trends',
    published: true,
  },
  {
    id: '2',
    title: 'The Rise of Smart Homes: Why Tech-Integrated Properties Sell Faster',
    excerpt: 'Smart home technology is no longer a luxury, but an expectation. Learn how integrating tech can increase your property value and appeal to modern buyers.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.',
    author: 'James Wilson',
    authorAvatar: 'https://i.pravatar.cc/150?u=11',
    date: 'Oct 08, 2023',
    image: 'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    category: 'Home Improvement',
    published: true,
  },
  {
    id: '3',
    title: 'Understanding Property Taxes: A Guide for First-Time Homebuyers',
    excerpt: 'Navigate the complex world of property taxes with our comprehensive guide designed specifically for those making their first real estate purchase.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.',
    author: 'Michael Chang',
    authorAvatar: 'https://i.pravatar.cc/150?u=12',
    date: 'Sep 28, 2023',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    category: 'Finance',
    published: true,
  },
  {
    id: '4',
    title: 'Minimalist Interior Design: Maximizing Space and Value',
    excerpt: 'Less is more. See how adopting a minimalist interior design can make spaces feel larger and more inviting to potential buyers or renters.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.',
    author: 'Sarah Jenkins',
    authorAvatar: 'https://i.pravatar.cc/150?u=13',
    date: 'Sep 15, 2023',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    category: 'Design',
    published: false,
  }
];
